### PR TITLE
Exlude Laravel 9 from PHP 7.4

### PR DESCRIPTION
**Pull request by thinkverse**
This PR excludes Laravel 9 from running on PHP 7.4, hopefully, that fixes your GH action. 🙂

### CODE REVIEW

**Comment by thinkverse** [comment]
@MohmmedAshraf seems to be more issues, I'll try and submit a quick PR before I go to bed to fix them. 👍

**Comment by MohmmedAshraf** [comment]
@thinkverse Thank you so much for your help, Sadly I am not very proficient with GitHub Actions

**Comment by thinkverse** [comment]
@MohmmedAshraf I think you're going to have to drop support for PHP 7.4 and only go with 8 and above. `wireui/wireui` has no v1 version that supports it, `laravel/pint` doesn't support it and your `blade-flags` don't support it either. the error for the [P7.4 - L8* run](https://github.com/MohmmedAshraf/laravel-translations/actions/runs/3881040140/jobs/6619627444) is pretty clear on that.

Is it OK to drop it and fix the rest? Should be just removing the PHP 7.4 part from the action and upping the require to `^8.0` instead of `^7.4`.

**Comment by MohmmedAshraf** [comment]
@thinkverse sound good, thank you

**Pull request merged**
