### PR TITLE
Routes enhancement and views return types added

### PR DESCRIPTION
**Pull request by shahghasiadil**

### CODE REVIEW

**Comment by MohmmedAshraf** [comment]
Thank you

**Comment by shahghasiadil** [comment]
@MohmmedAshraf there's a good issue to work on it but I'm not familiar with Livewire

**Comment by MohmmedAshraf** [comment]
@shahghasiadil I would like to help you resolve the issue, Can you please provide more information about the issue, such as error messages or reproduction steps, so that I can better understand the problem and work on finding a solution?

**Comment by shahghasiadil** [comment]
@MohmmedAshraf 
I want run php artisan translation:import from ui side when non of the import exists
there will be a button for import translate once clicked on it and it will run import command if command failed it won't be imported otherwise it will import the translations
I think I can do it in Livewire too but let's try

**Comment by shahghasiadil** [comment]
@MohmmedAshraf laravel has this feature when you're accessing model and migration isn't migrated they say run this command from ui side

**Pull request merged**
